//
//  MainViewController.swift
//  App target only. Exists for one reason: to register LiveActivityPlugin.
//
//  Capacitor on iOS registers plugins ONLY from the packageClassList array in
//  the capacitor.config.json inside the built bundle. There is no Objective-C
//  runtime scan; see registerPlugins() in CapacitorBridge.swift. That file is
//  generated by `npx cap copy ios`, is gitignored, and is rebuilt from the
//  npm-installed Capacitor packages every time the command runs.
//
//  LiveActivityPlugin is not an npm package. It is a class in this target. So
//  `cap copy` cannot know about it and silently drops it from the list, and a
//  plugin that is not in the list is simply absent from
//  window.Capacitor.Plugins. The web layer's null guards turn that into a
//  no-op with no crash and no log: the Live Activity just never starts. That
//  cost a full debugging session on 2026-08-07 while the plugin was compiled,
//  linked, entitled and correct.
//
//  Registering the instance here instead means the feature does not depend on
//  a generated file at all. Run `cap copy` as often as you like.
//

#if DEBUG
import ActivityKit
import UserNotifications
#endif
import Capacitor
import UIKit

class MainViewController: CAPBridgeViewController {
    // Called once the webview and bridge exist, before the webview is added to
    // the hierarchy, which is early enough for the plugin to be in place by
    // the time the page's JS runs.
    override func capacitorDidLoad() {
        super.capacitorDidLoad()
        let liveActivity = LiveActivityPlugin()
        bridge?.registerPluginInstance(liveActivity)
        liveActivity.registerNotificationCategories()
        // Registration fails silently if the plugin ever stops conforming to
        // CAPBridgedPlugin, and a silent failure here is exactly the bug this
        // file exists to prevent. One line, one os_log, worth keeping.
        NSLog("[Flukelogs] LiveActivity plugin registered: %@",
              bridge?.plugin(withName: "LiveActivity") != nil ? "YES" : "NO")
    }
}

/*
  Debug-only harness for the Live Activity, used to reproduce the lock screen
  passcode bug of 2026-08-09 without needing a signed-in session: the activity
  and its buttons are pure ActivityKit and never required a login, only the
  path that normally starts them did.

  DEBUG + environment gated twice over, so it cannot exist in a release build
  and cannot fire in a debug build unless launched with FL_LA_TEST=1.
*/
#if DEBUG
extension MainViewController {
    override public func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        guard ProcessInfo.processInfo.environment["FL_LA_TEST"] == "1" else { return }
        // The store as this launch sees it. Comparing this line before and
        // after a locked tap answers "did the intent run at all" without any
        // repaint working.
        let d = UserDefaults(suiteName: DiveTimerStore.appGroup)
        NSLog("[FL_LA_TEST] store: dive_started_at=%@ history=%@",
              String(describing: d?.object(forKey: "dive_started_at")),
              String(describing: d?.array(forKey: "dive_history_seconds")))
        if #available(iOS 16.2, *) {
            let attributes = TripActivityAttributes(
                tripStartedAt: Date(),
                boatName: "Test Boat"
            )
            var state = TripActivityAttributes.ContentState(
                positionText: "N 36 36.000 W 121 54.000",
                distanceNm: 1.2,
                diveStartedAt: nil,
                expectedSurfacing: nil,
                lastDiveSeconds: nil
            )
            DiveTimerStore.pushDiveState(into: &state)
            do {
                _ = try Activity<TripActivityAttributes>.request(
                    attributes: attributes,
                    content: ActivityContent(state: state, staleDate: nil)
                )
                NSLog("[FL_LA_TEST] test activity requested OK")
                // And the fence prompt, so its buttons can be inspected on a
                // simulator lock screen without a trip or a login.
                if let plugin = bridge?.plugin(withName: "LiveActivity") as? LiveActivityPlugin {
                    UNUserNotificationCenter.current().requestAuthorization(options: [.alert, .sound]) { _, _ in
                        let call = CAPPluginCall(callbackId: "fl-la-test", options: [:], success: { _, _ in }, error: { _ in })
                        plugin.promptStillLogging(call!)
                    }
                }
            } catch {
                NSLog("[FL_LA_TEST] activity request FAILED: %@", error.localizedDescription)
            }
        }
    }
}
#endif
