//
//  MainViewController.swift
//  App target only. Exists for one reason: to register LiveActivityPlugin.
//
//  Capacitor on iOS registers plugins ONLY from the packageClassList array in
//  the capacitor.config.json inside the built bundle. There is no Objective-C
//  runtime scan; see registerPlugins() in CapacitorBridge.swift. That file is
//  generated by `npx cap copy ios`, is gitignored, and is rebuilt from the
//  npm-installed Capacitor packages every time the command runs.
//
//  LiveActivityPlugin is not an npm package. It is a class in this target. So
//  `cap copy` cannot know about it and silently drops it from the list, and a
//  plugin that is not in the list is simply absent from
//  window.Capacitor.Plugins. The web layer's null guards turn that into a
//  no-op with no crash and no log: the Live Activity just never starts. That
//  cost a full debugging session on 2026-08-07 while the plugin was compiled,
//  linked, entitled and correct.
//
//  Registering the instance here instead means the feature does not depend on
//  a generated file at all. Run `cap copy` as often as you like.
//

import Capacitor
import UIKit

class MainViewController: CAPBridgeViewController {
    // Called once the webview and bridge exist, before the webview is added to
    // the hierarchy, which is early enough for the plugin to be in place by
    // the time the page's JS runs.
    override func capacitorDidLoad() {
        super.capacitorDidLoad()
        let liveActivity = LiveActivityPlugin()
        bridge?.registerPluginInstance(liveActivity)
        liveActivity.registerNotificationCategories()
        // Registration fails silently if the plugin ever stops conforming to
        // CAPBridgedPlugin, and a silent failure here is exactly the bug this
        // file exists to prevent. One line, one os_log, worth keeping.
        NSLog("[Flukelogs] LiveActivity plugin registered: %@",
              bridge?.plugin(withName: "LiveActivity") != nil ? "YES" : "NO")
    }
}
